version: "3.4"

services:

  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:latest
    restart: always
    networks:
      - default
    env_file:
      - kong/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    build: kong
    command: "kong migrations bootstrap"
    networks:
      - default
    restart: on-failure
    env_file:
      - kong/.env
    links:
      - kong-database
    depends_on:
      - kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    build: kong
    restart: always
    networks:
      - default
    env_file:
      - kong/.env
    environment:
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-migration
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8001:8001"
      - "8000:8000"

  keycloak-db:
    image: postgres
    env_file:
      - authentication/.env
    networks:
      - default
    ports:
      - "25432:5432"

  keycloak:
    build:
      context: authentication
      dockerfile: Dockerfile
    env_file:
      - authentication/.env
    networks:
      - default
    ports:
      - "8080:8080"