version: '3.4'

networks:
  default:
    driver: bridge
volumes:
  kong-datastore:
  elasticsearch:

services:
  api:
    build: api
    networks:
      - default
    volumes:
      - ./api/:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    ports:
      - 5000:5000
    env_file:
      - .env
  front:
    build:
      context: front/frontend
      dockerfile: Dockerfile
    volumes:
      - ./front/frontend/:/usr/src/app/
    networks:
      - default
    ports:
      - 3000:3000
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - .env
