version: '3.4'

networks:
  default:
    driver: bridge
volumes:
  kong-datastore:
  elasticsearch:

services:
  kong-db:
    image: postgres
    volumes:
      - kong-datastore:/var/lib/postgresql/data
    networks:
      - default
    ports:
      - "15432:5432"
    env_file:
      - kong/.env
  kong:
    build: kong
    networks:
      - default
    env_file:
      - kong/.env
    ports:
      - "8000:8000" # Listener
      - "8001:8001" # Admin API
      - "8002:8002" # Admin API
  api:
    build: api
    networks:
      - default
    volumes:
      - ./api/:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]

  keycloak-db:
      image: postgres
      env_file:
        - authentication/.env
      networks:
        - default
      ports:
        - "25432:5432"

  keycloak:
      build:
        context: authentication
        dockerfile: Dockerfile
      env_file:
        - authentication/.env
      networks:
        - default
      ports:
      - "8080:8080"

  front:
    build:
      context: front
      dockerfile: front/Dockerfile.nginx
    volumes:
      - ./front/dist/:/etc/nginx/html/dist/
      - ./front/data/nginx/:/etc/nginx/conf.d
    networks:
      - default
    ports:
      - 7777:7777