version: '3.4'

networks:
  default:
    driver: bridge

services:
  kong-provision:
    build:
      context: kong/docker
      dockerfile: Dockerfile.provision
    env_file:
      - kong/.env
      - authentication/.env
    networks:
      - default