version: '3.4'

networks:
  default:
    driver: bridge

services:
    minio:
      container_name: minio
      image: quay.io/minio/minio
      ports:
          - 9000:9000
          - 9001:9001
      environment:
        MINIO_ROOT_USER: root
        MINIO_ROOT_PASSWORD: rootpassword
      command: server /data --console-address :9001

    api:
      build: .
      networks:
        - default
      volumes:
        - ./app/:/app
      command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
      ports:
      - "5000:5000"