version: "3.4"

services:
  keycloak-db:
      image: postgres
      env_file:
        - .env
      networks:
        - default
      ports:
        - "25432:5432"

  keycloak:
      build:
        context: .
        dockerfile: Dockerfile
      env_file:
        - .env
      networks:
        - default
      ports:
      - "8080:8080"
